// Observer contract: current React tree, real totals, unknown data and no writes.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
let phase='phase-title',paused=false,canvas=null;
const document={querySelector(selector){if(selector==='main')return {className:phase};if(selector==='canvas')return canvas;if(selector==='.pause-panel')return paused?{}:null;},querySelectorAll(){return [];}};
const context={window:{},document};vm.createContext(context);
vm.runInContext(fs.readFileSync('assets/telemetry.js','utf8'),context);
const sample=()=>JSON.parse(JSON.stringify(context.window.thorDashboard.snapshot()));
assert.equal(sample().status,'title');phase='phase-playing';assert.equal(sample().status,'unavailable');
const live={player:{hp:3,maxHp:7,x:200,y:100},width:800,height:400,equipment:{hat:null,ring:[{id:'test-ring'},{id:'second-ring'}]},kamas:42,level:8,wave:3,phase:'playing'};
const hud={equipment:live.equipment,statBreakdowns:{critical:{detail:'Actuellement : +21 % · Avant plafond : +28 %',gear:'+7 %'}}};
const original=JSON.stringify({live,hud});
const mounted={memoizedState:{memoizedState:{current:live},next:{memoizedState:hud,next:null}}};
// The canvas property can point to the older fiber; the root.current is authoritative.
const root={stateNode:{current:{child:mounted}}};canvas={getBoundingClientRect:()=>({left:20,top:30,width:400,height:200}),__reactFiberTest:{return:root,memoizedState:{current:{player:{hp:99}}}}};
let value=sample();assert.equal(value.hp,3);assert.equal(value.kamas,42);assert.equal(value.items.length,2);
assert.equal(value.stats.find(s=>s.name==='Critique').value,'+21 %');
assert.equal(value.stats.find(s=>s.name==='Vitesse').value,null);
assert.equal(JSON.stringify({live,hud}),original);
const position=()=>JSON.parse(JSON.stringify(context.window.thorDashboard.playerPosition()));
assert.deepEqual(position(),{x:120,y:80});
live.player.x=300;assert.deepEqual(position(),{x:170,y:80});
const ref=mounted.memoizedState.memoizedState;
ref.current={...live,player:{...live.player,x:400}};assert.deepEqual(position(),{x:220,y:80});ref.current=live;
live.width=0;assert.equal(position(),null);live.width=800;
live.player.angle=Math.PI/2;live.upgrades={dashRange:2,jumpRange:1};live.awakenings={dash:3};
live.player.teleportReturnTimer=1;live.player.teleportReturnX=100;live.player.teleportReturnY=60;
const travel=JSON.parse(JSON.stringify(context.window.thorDashboard.travelState()));
assert.equal(travel.scaleX,.5);assert.equal(travel.scaleY,.5);assert.equal(travel.angle,Math.PI/2);
assert.deepEqual(travel.returnTarget,{x:70,y:60});assert.equal(travel.upgrades.dashRange,2);
live.player.teleportReturnTimer=0;assert.equal(context.window.thorDashboard.travelState().returnTarget,null);
paused=true;assert.equal(sample().phase,'paused');
let now=1000;context.Date={now:()=>now};hud.awakenings={burningGlyph:1};assert.equal(context.window.thorDashboard.abilities().awakenings.burningGlyph,1);hud.awakenings={burningGlyph:2};assert.equal(context.window.thorDashboard.abilities().awakenings.burningGlyph,1);assert.equal(context.window.thorDashboard.abilities(true).awakenings.burningGlyph,2);hud.awakenings={burningGlyph:3};now+=251;assert.equal(context.window.thorDashboard.abilities().awakenings.burningGlyph,3);
hud.statBreakdowns.critical.detail='Currently: +21 % · Before cap: +28 %';assert.equal(sample().stats.find(s=>s.name==='Critique').value,'+21 %');hud.statBreakdowns.critical.detail='Actualmente: +21 % · Antes del límite: +28 %';assert.equal(sample().stats.find(s=>s.name==='Critique').value,'+21 %');
live.player.hp=NaN;assert.equal(sample().status,'unavailable');
canvas=null;assert.equal(sample().status,'unavailable');
console.log('Telemetry observer contract passed.');
